spring:  
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: softhausit-zenite-kafka-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    producer:
      bootstrap-servers: 10.50.53.27:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
     mongodb:
       authentication-database: admin
       database: zenite-contratos
       host: 127.0.0.1
       password: ZeniteMongoSofthausIT2024
       port: 27017
       repositories.enabled: true
       username: zenite-admin     
      
  mvc:
    throw-exception-if-no-handler-found: true    
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      
elasticsearch.url: http://localhost:9200/_bulk