spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
      client: 
        registration:
          keycloak:
            provider: keycloak
            client-name: devedores-service
            client-id: devedores-service
            client-secret: e2e9be83-bd9d-4e91-9443-91794be06823
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"        
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/master            
            user-name-attribute: preferred_username
  kafka:
    consumer:
      bootstrap-servers: 10.50.53.27:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    producer:
      bootstrap-servers: 10.50.53.27:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
     mongodb:
       authentication-database: admin
       database: serco-app-dev
       host: 10.50.53.27
       password: Softhausit!2019!
       port: 27017
       repositories.enabled: true
       username: root
     elasticsearch:
      client:
        reactive:
          endpoints: '10.50.53.27:9200'
          username: 'elastic'
          password: 'changeme'
      cluster-name: 'searchtec-serco-cluster'
      cluster-nodes: '10.50.53.27:9200'
      repositories.enabled: true 
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8090/eureka
      
logstash.host: 10.50.53.27
logstash.port: 5000
logging.level.org.springframework: ERROR
logging.level.com: DEBUG
elasticsearch.url: http://10.50.53.27:9200/_bulk    