spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: softhausit-zenite-kafka-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:     
     elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          username: 'elastic'
          password: 'changeme'
      cluster-name: 'softhausit-zenite-cluster'
      cluster-nodes: '10.50.53.27:9200'
      repositories.enabled: true
      
  mvc:
    throw-exception-if-no-handler-found: true    
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      
elasticsearch.url: http://localhost:9200/_bulk