spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: ES256
          issuer-uri: http://10.50.53.27:8080/auth/realms/master
          jwk-set-uri: http://10.50.53.27:8080/auth/realms/master/protocol/openid-connect/certs
      client: 
        registration:
          keycloak:
            provider: keycloak
            client-name: registros-service
            client-id: registros-service
            client-secret: b3553ea2-ac19-415a-b67d-b834d09abf12
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"        
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/master            
            user-name-attribute: preferred_username
  kafka:
    consumer:
      bootstrap-servers: 10.50.53.27:29092
      group-id: searchtec-serco-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    producer:
      bootstrap-servers: 10.50.53.27:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
     mongodb:
       authentication-database: admin
       database: serco-app-dev
       host: 10.50.53.27
       password: Softhausit!2019!
       port: 27017
       repositories.enabled: true
       username: root
       
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8090/eureka
      
logstash.host: 10.50.53.27
logstash.port: 5000
logging.level.org.springframework: ERROR
logging.level.com: DEBUG
elasticsearch.url: http://10.50.53.27:9200/_bulk    