spring:
  data:
     mongodb:
       database: zenite-cluster
       host: mongodb+srv://zenite-admin-app:LDP3yITXKR7RR21b@zenite-cluster.swe3yyp.mongodb.net/?retryWrites=true&w=majority&appName=zenite-cluster       
             
eureka:
  client:
    serviceUrl:
      defaultZone: https://zenite-discovery-server.azurewebsites.net/eureka
      
#logstash.host: localhost
#logstash.port: 5000
logging.level.org.springframework: ERROR
logging.level.com: DEBUG
#elasticsearch.url: http://localhost:9200/_bulk  
