spring:
  data:
     mongodb:
       database: zenite-remessas
       uri: mongodb://zenite-admin:ZeniteMongoSofthausIT2024@localhost:27017/
             
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      
#logstash.host: localhost
#logstash.port: 5000
logging.level.org.springframework: ERROR
logging.level.com: DEBUG
#elasticsearch.url: http://localhost:9200/_bulk  
